-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#131318",
	base01 = "#0e0e13",
	base02 = "#1b1b21",
	base03 = "#47464f",
	base04 = "#c8c5d0",
	base05 = "#e4e1e9",
	base06 = "#303036",
	base07 = "#39383f",

	base08 = "#ffb4ab",
	base09 = "#e9b9d3",
	base0A = "#c6c4dd",
	base0B = "#c1c1ff",
	base0C = "#5f3c51",
	base0D = "#404178",
	base0E = "#454559",
	base0F = "#93000a",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#404178",
	fg = "#131318",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#585992",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#0e0e13",
	fg = "#c1c1ff",
})
