-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#18120b",
	base01 = "#130d07",
	base02 = "#211b13",
	base03 = "#4f4539",
	base04 = "#d3c4b4",
	base05 = "#ede0d4",
	base06 = "#362f27",
	base07 = "#3f3830",

	base08 = "#ffb4ab",
	base09 = "#b9cda0",
	base0A = "#ddc2a1",
	base0B = "#f5bc6f",
	base0C = "#3b4c29",
	base0D = "#633f00",
	base0E = "#56432b",
	base0F = "#93000a",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#633f00",
	fg = "#18120b",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#805610",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#130d07",
	fg = "#f5bc6f",
})
